apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBP55tWfTyoTQj5dYBwxnnMVlEOA2PD6hGLtJ35nuAcl5161TuYQ12okMee/++5Ryt+K+sjcMRnqn8vV98oiivg3d44MkRVi9JvivG/GqEeHjk5HFL8UUw0r3tw8R5QWggDk/+6jfc0HsBs/MbeABTVHJUvdxPDC9t458Y6Y+3uddaSwt5uAz6acJOX8lVxb08YUsiHyi66W/8fdZJpv0KZiO/83yytrvow4Y2e1xcTjyc/pSNbqF3Jlyg1KhHtEk47jr2DJY5kab1whztjarlqId+h44oHXnE0fomx4pq15AH/oX2A5oIRg1N9T6oANdyyyjyJUoEecN+lk42dP/3KrnEG00YnU+NMvl4BP6uvGVcr+E+K9dsRInro8aV4KcUDF4n2Z82jRAnFy35Lh+CB1eLHYKbIrZL8y5IWhb7UBKuyUDgsC7FVOGweqtXM16s2nsweOPQ1LZ4G9fERAbxQdu5K5ObeEUPUPjwQD4j11JvKPk+l4zZOw98xZ4sFhBq4Wcq1R9fK6CMP5j76IFjUuuwGPweJ01BaTrI3kx0bAI7MPNNPRQN1TNNr0MCWN7e0+B2gH0qPNKYCeT4vM75xEDEwMzJhgCoxkHyz+FfZ1/7n+OBnZURqfwfyhi3tlm8fkn7hEi+AsqSnTyjrJFVxXxjvEH+qDwfSDLzjwJsXWTcX6+WrG2pTH+rcOUmBCjnh29AXDADm0vZlvzahG6nl+Sbyxi4jGzMAt8wnL/OcjmTehPtGKLvj9kjTjyXzaE3ksN6ZT4sTS8FpkX4Sr610xsIXzeS065NOOphGesQRX6FkH+s+3htTXFilOX0teVQgyG1rys5aR3n+zAmDCRLf6L5oZiiqkkeHoagRP7f54khpECbly/2+CkXK0CvbsA61Y0zJfbP3ivCn9eZnrJjWn/uGHULYXLS9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

