apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB6LT7gH7dIKrK27750ZJzOJeP1XKv5LXeVR0OF6Xwtajk2MrUF0eGoJdMpsQNiOFrGQfuKhCehQGuLiOHDqN6PGEXv5DSLXesbVNC8Jnas4+ma0QnJypHTcv0Hrp36Y5DGySEiv0ylIksXO7MA0IgL2CH/33+FcbMI7bqX+Jjy9yfX8OwUkR+dImmAs5oK55qAB1Ef23WNXGWbsyUNKUFoW+0X7NUpgutUYIiSV1B0QR9xIcX3pPefvvSwBRsbxSDBHqFzRxTsUrpwTuDaFh59m1yEJSYrIxmX+jgLdaHXUUInn6l44DJwWY1NlvKOI6F4u2ECI3xayaIsroiH6IqHsidNuWmpGYe8FxZZTJJyOSrTywy4PRFE9E+6EKwQYvOPMnYZe0pliQ1NNqr12Ro4wVkgbyUyMl78kRg2v9QMw6YkiRBEhUofHjYmu0Uqa11dPAK7WXGCsQ1Fsc5puYLTKWwtafgvGXAkodQzvPJzM8RJeTb962B4R0q8P+HftdV0a6dznJNBVp5nG/7QicxZSOMXCOYqY2XB05A9AWtqXQj6bwDdEoh3TtN9oafl/mrKmOVuVJmzHJDjLSVl7eHexfPiRe+BZhLU5fC/uW0anZKZvE4rdcvzGxetuf9ITzqfTrNaHdON6hJgvnHXe0qH7ggzh5Zr2dc81xiyaMO+SLRCqiii4AInCwr6VquG+SHHHOJRBQkpWL1I0TRQeIAWJYaQl68L0T7EHDUN6dq6XKsGEeKKO5Gs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

